'use client';
import './globals.css'
import '../node_modules/bulma/css/bulma-rtl.min.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from './components/header/Navbar'
import { Inter } from 'next/font/google'
//fontawesome library 
import { library } from '@fortawesome/fontawesome-svg-core'

// import your icons
import { fab } from '@fortawesome/free-brands-svg-icons'
import { fas } from '@fortawesome/free-solid-svg-icons'
import { far } from '@fortawesome/free-regular-svg-icons'


import { store } from './store/store'
//import { Providers } from './store/provider'
import { useSelector, Provider } from 'react-redux';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  //const showCart = useSelector((state) => state.cartWindow.cartWindowIsOpen)
  return (
    
      <html lang="en">
        <body className={inter.className}> 
          <Provider store={store}>
            <Navbar/>
            {
              //showCart && <Carts/>
            }
            {children}
          </Provider>
        </body>
      </html>
    
  )
}


/* library.add(fab, fas, far) */